name: css
description: "A CSS library for Flutter that facilitates minimal code styling of widgets, simplifying the development of consistent and elegant UI."
version: 1.0.1
homepage: https://marhaendev.com
repository: https://github.com/marhaendev/dart-css

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true